version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.65.0
    - 0.66.0
  - dependency-name: react-native-screens
    versions:
    - 2.17.1
    - 2.18.0
    - 3.0.0
    - 3.1.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.21.0
    - 7.23.0
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.13.8
    - 7.13.9
  - dependency-name: react-native-reanimated
    versions:
    - 2.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
  - dependency-name: react-native-gesture-handler
    versions:
    - 1.10.1
  - dependency-name: "@react-navigation/stack"
    versions:
    - 5.14.1
    - 5.14.2
  - dependency-name: "@react-navigation/native"
    versions:
    - 5.9.2
  - dependency-name: react-native-paper
    versions:
    - 4.7.1
  - dependency-name: react-native-vector-icons
    versions:
    - 8.0.0
